name: Test Size Label Script

on:
  pull_request_target:

jobs:
  label-by-size:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run size label action (remote)
        uses: iahmedsabry/size-label@v1
        with:
          input_sizes: '{"0":"XS","20":"S","50":"M","200":"L","800":"XL","2000":"XXL"}'
          debug_action: 'true'
